# Generated by Django 3.1.4 on 2021-01-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='lang',
            field=models.FloatField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='lat',
            field=models.FloatField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
