# Generated by Django 3.1.4 on 2021-01-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='lang',
            field=models.FloatField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='lat',
            field=models.FloatField(max_length=15, null=True),
        ),
    ]
