# Generated by Django 3.1.4 on 2021-01-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20210120_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='Deliver_Type',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('No Delivery', 'No Delivery')], max_length=15),
        ),
    ]
