# Generated by Django 3.1.4 on 2021-01-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20210122_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='Food_Type',
        ),
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
