# Generated by Django 3.1.4 on 2021-01-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='address',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
