# Generated by Django 3.1.4 on 2021-01-09 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorprofile',
            old_name='Donar_Employmenr_Type',
            new_name='Donar_Employment_Type',
        ),
    ]
