# Generated by Django 3.1.4 on 2021-01-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_donorprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprofile',
            name='address',
            field=models.CharField(default='country/city/street', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charityprofile',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
