# Generated by Django 3.1.4 on 2021-01-22 21:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210109_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprofile',
            name='license',
            field=models.ImageField(default=' ', upload_to=accounts.models.image_upload),
            preserve_default=False,
        ),
    ]
