# Generated by Django 3.1.4 on 2021-01-22 19:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210122_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprofile',
            name='license_image',
            field=models.ImageField(default='default.jpg', upload_to=accounts.models.image_upload),
        ),
    ]
