# Generated by Django 3.1.4 on 2021-01-22 19:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20210122_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('family_memebers_numbers', models.IntegerField(default=1, help_text='Family Members')),
                ('address', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=0, help_text='Salary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.charityprofile')),
            ],
        ),
    ]
