# Generated by Django 3.1.4 on 2021-01-06 17:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('family_memebers_numbers', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=50)),
                ('work_status', models.CharField(choices=[('unemployed', 'unemployed'), ('employed', 'employed')], max_length=15)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
