# Generated by Django 3.1.4 on 2021-01-06 19:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='social_state',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
