# Generated by Django 3.1.4 on 2021-01-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_charityprofile_license'),
        ('beneficiary', '0002_auto_20210106_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='age',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='social_state',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='work_status',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.charityprofile'),
            preserve_default=False,
        ),
    ]
