# Generated by Django 3.1.4 on 2021-01-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_charityprofile_license'),
        ('beneficiary', '0005_remove_beneficiary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.charityprofile'),
            preserve_default=False,
        ),
    ]
